import { BatSide13 } from "./bat-side13";
import { PitchHand13 } from "./pitch-hand13";
import { PrimaryPosition13 } from "./primary-position13";
import { Stat10 } from "./stat10";

export interface Batter2 {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCity: string;
    birthStateProvince: string;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition13;
    useName: string;
    middleName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat10[];
    mlbDebutDate: string;
    batSide: BatSide13;
    pitchHand: PitchHand13;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    nameMatrilineal: string;
    pronunciation: string;
    nickName: string;
    nameTitle: string;
}
