import { BatSide4 } from "./bat-side4";
import { PitchHand4 } from "./pitch-hand4";
import { PrimaryPosition4 } from "./primary-position4";
import { Stat4 } from "./stat4";

export interface Batter {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition4;
    useName: string;
    middleName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat4[];
    batSide: BatSide4;
    pitchHand: PitchHand4;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    birthCity: string;
    birthStateProvince: string;
    mlbDebutDate: string;
    nameMatrilineal: string;
    pronunciation: string;
    nickName: string;
}