import { Broadcast } from './broadcast';
import { Content } from './content';
import { Decisions } from './decisions';
import { Flags } from './flags';
import { GameUtils } from './game-utils';
import { HomeRun } from './home-run';
import { Linescore } from './linescore';
import { Review } from './review';
import { SeriesStatus } from './series-status';
import { Status } from './status';
import { Teams } from './teams';
import { Venue3 } from './venue3';

export interface Game {
  sortIndex1: number;
  sortIndex2: number;
  sortIndex3: number;
  sortIndex4: number;
  sortIndex5: number;
  teams: Teams;
  gamePk: number;
  link: string;
  gameType: string;
  season: string;
  gameDate: Date;
  officialDate: string;
  status: Status;
  linescore: Linescore;
  decisions: Decisions;
  venue: Venue3;
  broadcasts: Broadcast[];
  content: Content;
  seriesStatus: SeriesStatus;
  isTie: boolean;
  gameNumber: number;
  publicFacing: boolean;
  doubleHeader: string;
  gamedayType: string;
  tiebreaker: string;
  calendarEventID: string;
  seasonDisplay: string;
  dayNight: string;
  scheduledInnings: number;
  reverseHomeAwayStatus: boolean;
  inningBreakLength: number;
  gamesInSeries: number;
  seriesGameNumber: number;
  seriesDescription: string;
  review: Review;
  flags: Flags;
  homeRuns: HomeRun[];
  recordSource: string;
  ifNecessary: string;
  ifNecessaryDescription: string;
  gameUtils: GameUtils;
  description?: string;
  homeTVArray: string[];
  awayTVArray: string[];
  homeTVDiv: string;
  awayTVDiv: string;
}
