import { BatSide6 } from "./bat-side6";
import { PitchHand6 } from "./pitch-hand6";
import { PrimaryPosition6 } from "./primary-position6";
import { Stat6 } from "./stat6";

export interface InHole {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCity: string;
    birthStateProvince: string;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition6;
    useName: string;
    middleName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat6[];
    batSide: BatSide6;
    pitchHand: PitchHand6;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    nameMatrilineal: string;
    mlbDebutDate: string;
    nickName: string;
    pronunciation: string;
}