import { BatSide11 } from "./bat-side11";
import { PitchHand11 } from "./pitch-hand11";
import { PrimaryPosition11 } from "./primary-position11";
import { Stat8 } from "./stat8";

export interface Loser {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCity: string;
    birthStateProvince: string;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition11;
    useName: string;
    middleName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat8[];
    batSide: BatSide11;
    pitchHand: PitchHand11;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    pronunciation: string;
    mlbDebutDate: string;
    nickName: string;
    nameTitle: string;
}
