import { BatSide5 } from "./bat-side5";
import { PitchHand5 } from "./pitch-hand5";
import { PrimaryPosition5 } from "./primary-position5";
import { Stat5 } from "./stat5";

export interface OnDeck {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCity: string;
    birthStateProvince: string;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition5;
    useName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat5[];
    batSide: BatSide5;
    pitchHand: PitchHand5;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    middleName: string;
    pronunciation: string;
    mlbDebutDate: string;
    nickName: string;
    nameTitle: string;
}
