import { BatSide } from "./bat-side";
import { PitchHand } from "./pitch-hand";
import { PrimaryPosition } from "./primary-position";
import { Stat } from "./stat";

export interface ProbablePitcher {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCity: string;
    birthStateProvince: string;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition;
    useName: string;
    middleName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat[];
    batSide: BatSide;
    pitchHand: PitchHand;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    nickName: string;
    mlbDebutDate: string;
    nameTitle: string;
    pronunciation: string;
    nameMatrilineal: string;
}