import { BatSide2 } from "./bat-side2";
import { PitchHand2 } from "./pitch-hand2";
import { PrimaryPosition2 } from "./primary-position2";
import { Stat2 } from "./stat2";

export interface ProbablePitcher2 {
    id: number;
    fullName: string;
    link: string;
    firstName: string;
    lastName: string;
    primaryNumber: string;
    birthDate: string;
    currentAge: number;
    birthCity: string;
    birthStateProvince: string;
    birthCountry: string;
    height: string;
    weight: number;
    active: boolean;
    alternateCaptain: boolean;
    captain: boolean;
    rookie: boolean;
    primaryPosition: PrimaryPosition2;
    useName: string;
    middleName: string;
    boxscoreName: string;
    gender: string;
    isPlayer: boolean;
    isVerified: boolean;
    draftYear: number;
    stats: Stat2[];
    mlbDebutDate: string;
    batSide: BatSide2;
    pitchHand: PitchHand2;
    nameFirstLast: string;
    nameSlug: string;
    firstLastName: string;
    lastFirstName: string;
    lastInitName: string;
    initLastName: string;
    fullFMLName: string;
    fullLFMName: string;
    strikeZoneTop: number;
    strikeZoneBottom: number;
    pronunciation: string;
    nameMatrilineal: string;
    nickName: string;
}